import localFont from 'next/font/local';
import type { Metadata } from 'next';
import '@/styles/index.css';

const syneSans = localFont({
    src: './fonts/SyneSansVF.ttf',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Phenomenon Next JS Template',
    description: 'Generated by create next app',
};

const RootLayout: React.FC<React.PropsWithChildren<unknown>> = ({ children }) => {
    return (
        <html lang="en">
            <body className={`${syneSans.className} antialiased`}>{children}</body>
        </html>
    );
};

export default RootLayout;
